added new specifiers
gmalecha/coq-printf pull request #1
Opened 2019-05-14 19:04 UTC by majorseitan

added a few more specifiers

2019-05-14 19:44 UTC, gmalecha requested changes
Thanks for the features. A few comments.

2019-05-14 19:44 UTC, gmalecha commented on theories/Justify.v
> +(* This impelementation was a helpful reference
Spelling.

2019-05-14 19:44 UTC, gmalecha commented on theories/Justify.v
> +Fixpoint drop (n : nat) (s : string) :=
This is `skipn` from the Coq standard library.

2019-05-14 19:44 UTC, gmalecha commented on theories/Justify.v
> +Fixpoint take (n : nat) (s : string):=
This is `firstn` from the standard library.

2019-05-14 19:44 UTC, gmalecha commented on theories/Justify.v
> +  intros.
All uses of tactics should be in a `Proof.`

2019-05-14 19:44 UTC, gmalecha commented on theories/Justify.v
> +Theorem length_sn : forall s a , length (String a s) = S(length s).
If you only rewrite this right to left, then you can replace it with `simpl`, or `simpl String.length`.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +(* Require Import Coq.omega.Omega. *)
Drop this line. `Omega` is deprecated anyways.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Record options := { option_justify : justify ;        (* '-'   : left justify                   x *)
It might make sense to move this (and the subsequent definitions) to another file since it is long.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Record options := { option_justify : justify ;        (* '-'   : left justify                   x *)
Also, probably a good idea to explicitly mark it `: Set`.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Definition default_options : options := {| option_justify :=  RightJustify ;
Probably make the indentation consistent.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Definition update_option_justify o v :=
You could use `coq-lens` to derive these...that would add another dependency though.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Inductive justify : Set := LeftJustify | RightJustify.
Blank line after imports. Also, add `Set Primitive Projections.`

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Inductive justify : Set := LeftJustify | RightJustify.
Change `Inductive` to `Variant` to avoid generation of induction schemes.

2019-05-14 19:44 UTC, gmalecha commented on theories/Printf.v
> +Definition format_s (s : string) (o : options) (x : string) : string :=
There seems to be a fair amount of repetition here. Does it make sense to essentially have two functions?

1. Convert the value (e.g. `nat`) to a string. For this you can use `ExtLib.Programming.Show`
2. Apply the `options`, i.e. `apply_options : options -> string -> string`

2019-05-15 14:29 UTC, majorseitan commented on theories/Justify.v
> +Fixpoint drop (n : nat) (s : string) :=
skpin works with lists and I have strings

2019-05-15 14:31 UTC, majorseitan commented on theories/Justify.v
> +Fixpoint take (n : nat) (s : string):=
firstn takes lists I have a string

2019-05-15 17:26 UTC, majorseitan commented on theories/Printf.v
> +Definition format_s (s : string) (o : options) (x : string) : string :=
I don't think Show supports multiple bases.  The options are a bit different for each specifier, I have tried to clean it up let me know your thoughts.

2019-05-15 17:27 UTC, majorseitan commented on theories/Printf.v
> +Definition default_options : options := {| option_justify :=  RightJustify ;
I think this is tab issue let me know if this persists.

2019-05-15 17:39 UTC, majorseitan commented on theories/Printf.v
> +Record options := { option_justify : justify ;        (* '-'   : left justify                   x *)
moved to Flags.v

2019-05-15 17:52 UTC, gmalecha commented on theories/Justify.v
> +Fixpoint take (n : nat) (s : string):=
Ah, thanks.

2019-05-15 17:54 UTC, majorseitan commented on theories/Printf.v
> +Definition update_option_justify o v :=
gonna skip for now as it coq-print is not in opam right so dependencies have to installed manually.

2019-05-15 17:56 UTC, gmalecha requested changes
Only two minor formatting issues.

2019-05-15 17:56 UTC, gmalecha commented on theories/Flags.v
> +Record options : Set := { option_justify : justify ;  (* '-'   : left justify                   x *)
This indentation is still inconsistent. I think you want to put the `{` on the next line.

2019-05-15 17:56 UTC, gmalecha commented on theories/Flags.v
> +Definition default_options : options := {| option_justify :=  RightJustify ;
The `{|` should go on the next line (consistency with the following definitions).

2019-05-16 01:28 UTC, gmalecha approved these changes
A few minor things, mostly formatting. Otherwise, it looks great. Thanks so much.

2019-05-16 01:28 UTC, gmalecha commented on theories/Flags.v
> +intros.
Missing `Proof.`

2019-05-16 01:28 UTC, gmalecha commented on theories/Justify.v
> +  Qed.
Why indent?

2019-05-18 19:26 UTC, merged

2019-05-18 19:26 UTC, gmalecha commented
Thanks!